### ISSUE TITLE
Great Idea

### ISSUE THREAD

**Issue by jasonhutchens** [Genki-S/ttnt#13]
Kudos on this idea!

I was once working on something similar (long abandoned), which used code coverage reports to generate Rake dependencies for running specs, cukes and asset compilation.

The really great benefit of this, apart from improving CI times, is that, when a test fails, you can use the dependencies along with the git diff to highlight the code that probably broke the test.

Good luck!

**Comment by Genki-S** [comment]
Hi jasonhutchens, thanks a lot for your Kudos!

That is awesome your project used code coverage to select not only tests but also asset compilation. It's so great that I might steal the idea, forgive me if that happens :wink: I would really appreciate if you could give me the code and/or description of the approach of your project! Please let me know if it's possible.

> when a test fails, you can use the dependencies along with the git diff to highlight the code that probably broke the test

This is super great idea! :+1: 
I definitely want to challenge this once I succeed to select tests. Thank you so much for sharing your idea!

Since I cannot start working on them soon, I created a Trello board ( https://trello.com/b/z232DXnq/ttnt ) to store your ideas for the future and I'm closing this issue for now. I will let you know when I can start working on them.
Thanks again for your comment! :smile:

**Comment by jasonhutchens** [comment]
:+1: thanks, I will try to get you something useful soon :)

**Comment by Genki-S** [comment]
Awesome! Thank you so much, I am looking forward to hearing from you again :smile:
