### ISSUE TITLE
Make .ttnt Rakefile-binded rather than Git-binded

### ISSUE THREAD

**Issue by robin850** [Genki-S/ttnt#32]
Hi!

At the moment, `TTNT::TestTask` will create a `.ttnt` file at the root of the Git repository. It would be cool to create this file according to the location of the Rakefile where it is instantiated.

The advantages are that, for most projects, the work-flow is the same as there's most of the time only one main `Rakefile` and for larger code base like Rails, there's a tinier mapping inside each file. Having only one mapping for the whole project in the case of Rails would be first costly to load through `JSON.load` and second, there would be too many versions of the file inside the Git history as it would be touched too often.

What do you think ?

Have a nice day!

**Comment by Genki-S** [comment]
That is actually a solution for the problem I am having right now :bulb: 
I'm trying to install TTNT to Rails and my problem is that when generating `.ttnt` for, say, ActionMailer, I have `.ttnt` in root directory, even though it does not contain mappings from other gems inside the repository. And when running `rake ttnt:test:run` in other gems, since there **is** `.ttnt` file but no mapping data inside, TTNT does not run any test. Too bad :disappointed_relieved: 

And your opinions regarding costly `JSON.load` and Git versioning are quite true, thank you for pointing out!
I will implement this right away :muscle: 

Have a nice day too :smile:

**Comment by Genki-S** [comment]
This is done as #34 :tada:
