### ISSUE TITLE
[Try] Store code-to-test mapping to a single file

### ISSUE THREAD

**Issue by Genki-S** [Genki-S/ttnt#4]
Idea from Robin.

Storing code-to-test mapping files as `.ttnt/code-to-test-mapping/BASE_COMMIT_SHA/TEST_FILE_NAME.json`
is too expensive. Having single file (e.g. `.ttnt/code-to-test-mapping.json`) and
updating it commit by commit is much simpler.

Concerns:

- That file will be super huge
- Not sure if I can utilize git efficiently (i.e. if I store json in one line, version control does not reduce file content size in total, I guess)

**Comment by robin850** [comment]
> That file will be super huge

Yes I agree but I guess Git will have to track too many files if we have a folder for each commit with a single coverage file for each test file. Given that we have 689 test files at the moment:

~~~
$ tree . | grep "_test.rb" | wc -l
689
~~~

we will have 689 * n files for n commits + n folders. While n revisions of a file of 689 lines seem to be cheaper because the content will not drastically change between commits.

A pretty important point also is that if the given SHA is for a documentation commit for example, there won't be any associated folder under `.ttnt` for it (as far as I understand ; this would be useless). Thus you will have to find the closest commit in the history that has coverage. With the single file approach, you just have to checkout the repository at a given commit and read the content of the file.

The only drawback here with the single file approach is that it's more expensive to get the coverage for a specific test since we have to load the whole file's content but I'm not sure whether this is a problem ; we just have to load the content once when we run the rake task.

> Not sure if I can utilize git efficiently (i.e. if I store json in one line, version control does not reduce file content size in total, I guess)

I'm not sure to understand what's the problem with Git here. Can you elaborate please ? :-)

**Comment by Genki-S** [comment]
> While n revisions of a file of 689 lines seem to be cheaper because the content will not drastically change between commits

You are right. My only concern here is the size of that single file may be over the max file size limited by OS.

I will stop storing files for each commit, but separating coverage files for each test file might be still an option. I will first try single file approach and see how the file size goes.

> Thus you will have to find the closest commit in the history that has coverage. With the single file approach, you just have to checkout the repository at a given commit and read the content of the file.

Genius! It has been my big problem how to find the latest commit that has coverage information. With your approach we can easily use e.g. merge-base as base commit to select tests. Thank you so much :laughing: 

> we just have to load the content once when we run the rake task.

I agree. Loading all coverage information might be a bit tough on memory, but I also think it's not a big problem. I'll deal with it if it turned out to be a problem :stuck_out_tongue: 

> I'm not sure to understand what's the problem with Git here. Can you elaborate please ? :-)

Sorry it was confusing. It was my mental note that if we version control the coverage file, we need a strategy to reduce the difference  so that patch size is minimized (maybe by sorting file contents). It's rather a TODO than a problem with git.

**Comment by robin850** [comment]
> My only concern here is the size of that single file may be over the max file size limited by OS.

We certainly have to do a bunch of optimizations to only store useful information inside the coverage file(s). We should discuss about that in another ticket but for instance, I think that we should only keep coverage that is directly related to the library. For instance, Active Support is used everywhere but we should not run the Action Mailer tests that depend on Active Support (otherwise we are running the whole suite whenever there's an Active Support change :smile: )

This drastically changes the size of the coverage:

~~~ruby
# With http://git.io/vIgz4 for instance
>> require 'json'
=> true
>> coverage = JSON.load(File.read("..."));
>> coverage.keys.length
=> 219
>> coverage.keys.keep_if { |k| k =~ /actionmailer/ }.length
=> 13
~~~

For sure this is not that simple for tied components (like Action View and Action Pack), but anyway, you get the idea. :-)

**Comment by Genki-S** [comment]
> We should discuss about that in another ticket

Yes, this deserves another ticket, thanks for mentioning. I've opened it here: #5

> For instance, Active Support is used everywhere but we should not run the Action Mailer tests that depend on Active Support

That's true. I think I don't want to be bothered by tests affected by changes in Active Support when I am developing Action Mailer.
However still, I might want to run tests affected by changes in Active Support, say, before submitting a pull request as a kind of light integration test.

In this case, I want users to act like this:

1. commit changes related to Active Support (let it COMMIT_A)
2. produce coverage information using TTNT
3. commit changes related to Action Mailer (let it COMMIT_B)
4. run TTNT with target commit COMMIT_B and base commit COMMIT_A (run tests affected by changes from COMMIT_A to COMMIT_B)

In this case, users can run tests only related to changes in Action Mailer. But it might be a lot for a user to think... What do you think?

**Comment by robin850** [comment]
I'm not sure to understand your second point regarding test limitation but actually I just wanted to say that we should not use other component's tests as tests for Active Support since it's used everywhere.

There's no problem here I guess ; if the user wants to run tests affected by changes between COMMIT_A and COMMIT_B, then TTNT will provide the tests that concern this changes-set (so somes tests under `activesupport/test` and some under `actionmailer/test`). The fact that some components are tied together should not be a problem for you ; we can just avoid storing coverage for external things when this is not useful. That's it! :-) If you don't understand something, feel free to ask. I'm not sure whether I'm clear enough!

**Comment by Genki-S** [comment]
Now I think I did understand... but let me check if I got it right.

For example, [GitLab](https://github.com/gitlabhq/gitlabhq) is using Rails and thus Active Support. When TTNT is used under GitLab, GitLab's test covers some code inside Rails. You are saying, in this case, TTNT should not store the information "GitLab's test A depends on code inside Rails" since this can cause TTNT runs GitLab's test A when there's a change inside Rails (say, they updated Rails). And this can increase the size of TTNT's test-to-code mapping file significantly. Am I getting it right?

If this is right, I think I have implemented it [here](https://github.com/Genki-S/ttnt/blob/master/lib/ttnt/test_to_code_mapping.rb#L56-L60) as `select_project_files` method. This method removes coverage information outside the project's repository (regarding one git repository as a project).

I think I was confused since Action Mailer and Active Support are in the same git repository. So, at last, I also guess there's no problem here :smile: Thank you so much for your thorough explanation :bow: (I hope I understand you right... Please let me know if I'm still misunderstand you :pray:)

**Comment by robin850** [comment]
> You are saying, in this case, TTNT should not store the information "GitLab's test A depends on code inside Rails" since this can cause TTNT runs GitLab's test A when there's a change inside Rails

That's actually the other way around ; if GitLab uses TTNT, it should not store Rails' components' paths inside the coverage file but yep, you got the idea. :-)

**Comment by Genki-S** [comment]
Oops, sorry for the mistake. But I guess I got the idea, thank you!

**Comment by robin850** [comment]
No problem! I take the liberty to close this one as #7 has been merged. :-)

**Comment by Genki-S** [comment]
Thanks! I'm sorry I'm being lazy closing issues :sweat: It's being messy so I think I should clean up issues.
